routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home')->middleware('auth');

//Route::get('/phpinfo', function(){ phpinfo(); });

Auth::routes();

/** Reports */
Route::group([ 'prefix' => 'reports', 'as' => 'reports.' , 'middleware' => ['auth']] , function() {    

    Route::get('/{professional_family}/andamento', ['as' => 'andamento', 'uses' => 'ReportController@andamento']);
    Route::get('/{professional_family}/professioni', ['as' => 'professioni', 'uses' => 'ReportController@professioni']);
    Route::get('/{professional_family}/aziende', ['as' => 'aziende', 'uses' => 'ReportController@aziende']);
    Route::get('/{professional_family}/esperienza', ['as' => 'esperienza', 'uses' => 'ReportController@esperienza']);
    Route::get('/{professional_family}/contratto', ['as' => 'contratto', 'uses' => 'ReportController@contratto']);
    Route::get('/{professional_family}/bilancio_competenze', ['as' => 'bilancio_competenze', 'uses' => 'ReportController@bilancio_competenze']);
    Route::get('/{professional_family}/top_competenze', ['as' => 'top_competenze', 'uses' => 'ReportController@top_competenze']);
    Route::get('/{professional_family}/regioni', ['as' => 'regioni', 'uses' => 'ReportController@regioni']);
    Route::get('/{professional_family}/geo_annunci_prov', ['as' => 'geo_annunci_prov', 'uses' => 'ReportController@geo_annunci_prov']);
    Route::get('/{professional_family}/geo_vdm_reg', ['as' => 'geo_vdm_reg', 'uses' => 'ReportController@geo_vdm_reg']);
    Route::get('/{professional_family}/geo_vdm_prov', ['as' => 'geo_vdm_prov', 'uses' => 'ReportController@geo_vdm_prov']);

    Route::get('/{professional_family}/professione_esco', ['as' => 'professione_esco', 'uses' => 'ReportController@professioneESCO']);
    Route::get('/{professional_family}/professione_istat', ['as' => 'professione_istat', 'uses' => 'ReportController@professioneISTAT']);        
    Route::get('/{professional_family}/salario', ['as' => 'salario', 'uses' => 'ReportController@salario']);
    Route::get('/{professional_family}/confronto', ['as' => 'confronto', 'uses' => 'ReportController@confronto']);
});

Route::group([ 'prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.' , 'middleware' => ['auth' , 'can:is_admin']] , function() {
    
    /** Users */
    Route::group([ 'prefix' => 'users', 'as' => 'users.'] , function() {
        Route::get('/index', ['as' => 'index', 'uses' =>'UserController@index']);
        Route::get('/create', ['as' => 'create', 'uses' =>'UserController@create']);
        Route::post('/store', ['as' => 'store', 'uses' =>'UserController@store']);
        Route::get('/{user_id}/edit', ['as' => 'edit', 'uses' =>'UserController@edit']);        
        Route::put('/update', ['as' => 'update', 'uses' =>'UserController@update']);
        Route::delete('/delete', ['as' => 'delete', 'uses' =>'UserController@delete']);
        Route::get('/{user_id}/reset_password', ['as' => 'reset_password', 'uses' =>'UserController@resetPassword']);
        Route::post('/change_password', ['as' => 'change_password', 'uses' =>'UserController@changePassword']);
    });
    
    /** Professional Families */
    Route::group([ 'prefix' => 'professional_families', 'as' => 'professional_families.'] , function() {
        Route::get('/index', ['as' => 'index', 'uses' =>'ProfessionalFamilyController@index']);
        Route::get('/create', ['as' => 'create', 'uses' =>'ProfessionalFamilyController@create']);
        Route::post('/store', ['as' => 'store', 'uses' =>'ProfessionalFamilyController@store']);
        Route::get('/{professional_family_id}/edit', ['as' => 'edit', 'uses' =>'ProfessionalFamilyController@edit']);
        Route::put('/update', ['as' => 'update', 'uses' =>'ProfessionalFamilyController@update']);
        Route::delete('/delete', ['as' => 'delete', 'uses' =>'ProfessionalFamilyController@delete']);
    });

    /** Professional Families */
    Route::group([ 'prefix' => 'imports', 'as' => 'imports.'] , function() {
        Route::get('/index', ['as' => 'index', 'uses' =>'ImportController@index']);
        Route::get('/create', ['as' => 'create', 'uses' =>'ImportController@create']);
        Route::post('/store', ['as' => 'store', 'uses' =>'ImportController@store']);        
    });    
    
});

app/Models/Import.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Import extends Model
{
    protected $fillable = [
        'id',
        'user_id',
        'professional_family_id',
        'rows',
        'filename'
    ];
    
    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [        
        'id' => 'integer',
        'user_id'  => 'integer',
        'professional_family_id'  => 'integer',
        'rows' => 'integer',
        'filename' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'user_id' => 'required',
        'professional_family_id' => 'required',
        'rows' => 'required',
        'filename' => 'required',
    ];

    public function user()
    {
        return $this->belongsTo(\App\Models\User::class);
    }

    public function professional_family()
    {
        return $this->belongsTo(\App\Models\ProfessionalFamily::class);
    }
}

app/Http/Controllers/Admin/ImportController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

use App\Http\Requests\ImportRequest;

use App\Repository\ImportRepositoryInterface;
use App\Repository\ProfessionalFamilyRepositoryInterface;

use File;
use DB;

class ImportController extends Controller
{

    private $importRepository; 
    private $professionalFamilyRepository; 

    public function __construct(ImportRepositoryInterface $importRepository, ProfessionalFamilyRepositoryInterface $professionalFamilyRepository)
    {        
        $this->importRepository = $importRepository;
        $this->professionalFamilyRepository = $professionalFamilyRepository;
    }

    public function index()
    {
        $imports = $this->importRepository->all();
        return view('admin.import.index', [
            'imports' => $imports
        ]);
    }

    public function create(){

        $professional_families = $this->professionalFamilyRepository->all()->pluck('name', 'id');

        $files = Storage::disk('local')->files('csv');        

        $files = array_map(function($v){ return basename($v); }, $files);
        
        return view('admin.import.create', [
            'professional_families' => $professional_families,
            'files' => array_combine(array_values($files), $files)
        ]);

    }

    public function store(ImportRequest $request)
    {
                    
        $professional_family = $this->professionalFamilyRepository->find($request['professional_family_id']);                

        $this->importRepository->createTable($professional_family->slug, $request['pre_import']);

        $path = storage_path('app/csv/'.$request['filename']);      
        
        //$data = array_map('str_getcsv', file($path));        
        $ins_rows = 0;
        
        if(File::exists($path)):                        
            
            $header = [];
            $data = array();            

            if (($handle = fopen($path, 'r')) !== FALSE):
            
                while (($row = fgetcsv($handle, 1000, ',')) !== FALSE)
                {
                    if(!$header):
                        $header = $row;
                    else:
                        $data_row = array_combine($header, $row);
                        
                        if( DB::table($professional_family->slug)->insert($data_row) ):
                            $ins_rows++;
                        endif;

                    endif;
                }
                fclose($handle);
            endif;
                  
        endif;

        $this->importRepository->create([
            'user_id' => $request['user_id'],
            'professional_family_id' => $professional_family->id,
            'rows' => $ins_rows,
            'filename' => $request['filename']
        ]);            
        
    

        return redirect(route('admin.imports.index'));
    }                
   
}

resources/views/admin/import/create.blade.php
@extends('layout.app')

@section('title', config('app.name') )

@section('content_header')
    <h1 class="m-0 text-dark">Importa CSV</h1>
    <p>Il file deve risiedere nella cartella /storage/app/csv</p>
@stop

@section('app-content')
<div class="row">
    <div class="col-md-12">        
        {!! Form::open(array('route' => array('admin.imports.store'), 'method' => 'POST' )) !!}                                    

            <div class="form-group">
                {!! Form::label('filename', 'Nome file') !!}
                {!! Form::select('filename', $files, null, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('professional_family_id', 'Famiglia professionale') !!}
                {!! Form::select('professional_family_id', $professional_families, null, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('pre_import', 'Pre-import') !!}
                {!! Form::select('pre_import', ['Crea la tabella se non esiste o svuotala se già presente', 'Aggiungi i dati a quelli esistenti'], null, ['class' => 'form-control']) !!}
            </div>
        
            <div class="form-group">
                <button type="submit" class="btn btn-lg btn-success">Importa</button>
                <a href="{{ route('admin.imports.index') }}" class="btn btn-lg btn-default">Annulla</a>
            </div>

        {!! Form::close() !!}
    </div>
</div>
@endsection

resources/views/admin/import/index.blade.php
@extends('layout.app')

@section('title', config('app.name') )

@section('content_header')
    <h1 class="m-0 text-dark">Importazioni CSV</h1>
@stop

@section('app-content')
<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <a href="{{ route('admin.imports.create') }}" class="btn btn-lg btn-primary"><i class="fas fa-file-import"></i> Nuova importazione</a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Eseguito da</th>
                    <th>Famiglia professionale</th>
                    <th>File</th>
                    <th>Righe importate</th>
                    <th>Data importazione</th>                    
                </tr>
            </thead>
            <tbody>
            @foreach($imports as $import)
                <tr>
                    <td>{{ $import->user->name }} {{ $import->user->surname }}</td>
                    <td>{{ $import->professional_family->name }}</td>
                    <td>{{ $import->filename }}</td>
                    <td>{{ $import->rows }}</td>
                    <td>{{ $import->created_at }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{ $imports->links() }}
    </div>
</div>
        
@endsection

@section('app-js')
<script>                    
</script>
@endsection